### ISSUE TITLE
Native host has exited. Exception: 'NoneType' object has no attribute 'unpack'

### ISSUE THREAD

**Issue by joistick11** [nE0sIghT/chrome-gnome-shell-mirror#35]
Hi guys
Third day I am trying to install the gnome-shell integration into my browser. Initially it didn't want to work on Ubuntu 15.04, the Chrome just hadn't seen the gnome-shell extension.
Now I've upgraded to Ubuntu 16.04 and at least it is starting working, but now I have an error on shell-extensions site: Native host has exited.
When I run chrome from terminal, I see the following:
`[11069] Uncaught exception of type <class 'AttributeError'> occured
  File "/usr/bin/chrome-gnome-shell", line 226, in on_input
    self.process_request(request)
  File "/usr/bin/chrome-gnome-shell", line 375, in process_request
    'shellVersion': shell_version.unpack(),
[11069] Exception: 'NoneType' object has no attribute 'unpack'
[1:1:0220/230142.826410:ERROR:KeyboardEventManager.cpp(424)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()
[1:1:0220/230312.135459:ERROR:KeyboardEventManager.cpp(424)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()
[11331] Uncaught exception of type <class 'AttributeError'> occured
  File "/usr/bin/chrome-gnome-shell", line 226, in on_input
    self.process_request(request)
  File "/usr/bin/chrome-gnome-shell", line 375, in process_request
    'shellVersion': shell_version.unpack(),
[11331] Exception: 'NoneType' object has no attribute 'unpack'`

I have no idea what can I do, google says nothing about this error in combination with gnome shell

Thank you in advance

**Comment by nE0sIghT** [comment]
Please show output of ```gnome-shell --version```

**Comment by joistick11** [comment]
GNOME Shell 3.18.5

**Comment by joistick11** [comment]
I've update gnome-shell, now it is GNOME Shell 3.20.4
But it is still not working

**Comment by nE0sIghT** [comment]
Please install ```d-feet``` package and run d-feet application.

1. Select ```Session Bus```
2. Type ```Shell``` in search box
3. Select ```org.gnome.Shell``` bus
4. Open ```/org/gnome/Shell``` interface
5. Double click on ```ShellVersion``` property and post here screenshot of d-feet window.

![selection_032](https://cloud.githubusercontent.com/assets/3389586/23171656/8da0efc6-f86c-11e6-9f0b-df1e341855bd.png)

**Comment by joistick11** [comment]
There are no Properties tab
![image](https://cloud.githubusercontent.com/assets/10850123/23172321/7234ea40-f866-11e6-9dd8-c0e259ff5fc9.png)

**Comment by nE0sIghT** [comment]
It looks like some bug in GNOME Shell. I will try to dig into it.

Your GNOME Shell also missing ```org.gnome.Shell.Extensions``` interface so you will not be able to install extensions anyway.

It's really strange behavior.

**Comment by nE0sIghT** [comment]
Hmm, I see that cmd line is "compiz" instead of "gnome-shell".

Do you have Unity or compiz installed? You should remove them.

**Comment by joistick11** [comment]
![image](https://cloud.githubusercontent.com/assets/10850123/23178835/ebc9b1b8-f87c-11e6-9db1-6f64abf0facc.png)

**Comment by nE0sIghT** [comment]
It's Unity desktop - that's why you can not use GNOME Shell integration and you can not install GNOME Shell extensions with Unity.

Look to some instruction to switch from Unity to GNOME like this: http://askubuntu.com/questions/766071/install-gnome-shell-on-ubuntu-16-04

Basically, you should install ```ubuntu-gnome-desktop``` and ```gdm``` and remove all ```unity``` packages

**Comment by nE0sIghT** [comment]
This issue can not be fixed for obvious reasons.
However I will add check for missing ShellVersion property so that connector will not crash, but you will see standard error message "GNOME Shell not found".

Reopen if you still have questions.

**Comment by joistick11** [comment]
Thank you a lot!
